# Generated by Django 5.1.1 on 2025-03-12 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_customuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speicalization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='specialization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='specs', to='app.speicalization'),
            preserve_default=False,
        ),
    ]
