# Generated by Django 5.1.1 on 2025-03-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_customuser_specialization_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Prefer Not To Say')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
