# Generated by Django 5.1.1 on 2025-03-13 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_customuser_gender_delete_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign', models.CharField(choices=[('$', 'Dollar'), ('€', 'Euro'), ('SP', 'Syrian Pound'), ('₺', 'Turkish Lira')], max_length=20)),
                ('service_type', models.CharField(choices=[('Hour', 'Hour'), ('Session', 'Session')], max_length=20)),
                ('about_me', models.TextField()),
                ('doc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_owner', to=settings.AUTH_USER_MODEL)),
                ('speicalization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_spec', to='app.speicalization')),
                ('languages', models.ManyToManyField(to='app.language')),
                ('nationalities', models.ManyToManyField(to='app.nationality')),
            ],
        ),
    ]
