# Generated by Django 5.1.7 on 2025-03-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_customuser_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
