# Generated by Django 5.1.7 on 2025-03-23 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_doctorprofile_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='doc',
        ),
    ]
